var xmlFile="partslist.xml";
var xslFile="parts_table.xsl"
var xmlDoc = null;
  


// generated by ChatGPT - with some prompting, but still impressive!

function generateTable(xml, xsl) {
    // Create an XSLT processor
    var xsltProcessor = new XSLTProcessor();
  
    // Import the stylesheet into the processor
    xsltProcessor.importStylesheet(xsl);
  
    // Transform the XML data using the stylesheet
    var fragment = xsltProcessor.transformToFragment(xml, document);
  
    // Insert the HTML into the page
    document.getElementById("table-partslist").appendChild(fragment);
}
  
function loadXML(file, callback) {
    var xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function() {
      if (this.readyState == 4 && this.status == 200) {
        callback(this.responseXML);
      }
    };
    xhttp.open("GET", file, true);
    xhttp.send();
}
  
// Load the XML and XSL files, then generate the table
loadXML(xmlFile, function(xml) {
    loadXML(xslFile, function(xsl) {
        generateTable(xml, xsl);
    });
});
  